### PR TITLE
initial project wave 0.0

### PR DESCRIPTION
**Pull request by rpavilanis**
https://trello.com/b/6JRDemNP

### CODE REVIEW

**Comment by droberts-ada** [comment]
I can't access your Trello board! Make sure you've shared it with me.

**Comment by rpavilanis** [comment]
Can you try it again?  I used a different link - I think this one might work.

**Comment by CheezItMan** [comment]
@rpavilanis Can you add me to your Trello Board?

**Comment by rpavilanis** [comment]
@CheezItMan Added you!

**Comment by CheezItMan** [comment]
@rpavilanis @miriam-cortes Looks good,

**Pull request closed without merging**
