### PR TITLE
Yuri & Maddie initial commit our branch

### PR DESCRIPTION
**Pull request by Ynakashima**
Initial file setup, Maddie has been added as collaborator

### CODE REVIEW

**Comment by kariabancroft** [comment]
Note that your base PR also needs to include an accessible link to your team's Trello board

**Comment by Ynakashima** [comment]
Link to Trello board:
https://trello.com/b/lUqa1y1p/c6-user-stories

**Comment by droberts-sea** [comment]
That's a link to the example trello board for TaskList we put up on the big screen. Please provide a link to your own board.

**Comment by Ynakashima** [comment]
Sorry about that. Here is the correct link:
https://trello.com/b/o5ohG8VR/farmar-rails

**Pull request merged**
